/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.ifba.JPATeste.view;

import br.com.ifba.JPATeste.ExceptionHandler.TarefaExceptions;
import br.com.ifba.JPATeste.Facade.TarefasFachadas;
import br.com.ifba.JPATeste.Models.Tarefas;
import java.util.Calendar;
import br.com.ifba.JPATeste.Instancias.TarefaInstance;
import javax.swing.JOptionPane;

/**
 *
 * @author lara
 */
public class Tela3 extends javax.swing.JDialog {

    private Tela1 tela1;
    private Tarefas tarefaToUpdate;
    private TarefasFachadas facade;

    public Tela3(Tela1 tela1, Tarefas tarefa) {
        super(tela1, true);
        facade = new TarefasFachadas();
        initComponents();
        this.tela1 = tela1;
        this.tarefaToUpdate = tarefa;
        setItemToUpdate(this.tarefaToUpdate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNewDesc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblFinal = new javax.swing.JLabel();
        bxFinal = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNewDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewDescActionPerformed(evt);
            }
        });

        jLabel1.setText("Nova Descrição:");

        lblFinal.setText("Finalizada?");

        bxFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNewDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bxFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFinal))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bxFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewDescActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            Tarefas tarefa = TarefaInstance.createInstance();//cria novo obj
            tarefa.setId(this.tarefaToUpdate.getId());//bota a id do novo obj como a doq foi selecionado
            if (!(txtNewDesc.getText().isEmpty())) {//verifica se descrição tm algo
                tarefa.setDescricao(txtNewDesc.getText());
            } else {
                JOptionPane.showMessageDialog(this, "DESCRIÇOA VAZIA", "Erro", JOptionPane.ERROR_MESSAGE);
            }

            if (bxFinal.getSelectedIndex() == 0) {
                tarefa.setFinalizado(true);
            } else if (bxFinal.getSelectedIndex() == 1) {
                tarefa.setFinalizado(false);
            }
            //mesma coisa de adc
            tarefa.setDataFinal(Calendar.getInstance());

            facade.update(tarefa);
            tela1.updateTable();
            dispose();
        } catch (TarefaExceptions ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnUpdateActionPerformed
    private void setItemToUpdate(Tarefas tarefa) {//seta o item q foi selecionado cmo os valores defalt(muda apenas oq o usuario mudar
        txtNewDesc.setText(tarefa.getDescricao());
        if (tarefa.isFinalizado()) {
            bxFinal.setSelectedIndex(0);
        } else {
            bxFinal.setSelectedIndex(1);
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> bxFinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFinal;
    private javax.swing.JTextField txtNewDesc;
    // End of variables declaration//GEN-END:variables
}
