/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.JPATeste.view;

import javax.swing.JOptionPane;
import br.com.ifba.JPATeste.ExceptionHandler.TarefaExceptions;
import br.com.ifba.JPATeste.Facade.TarefasFachadas;
import br.com.ifba.JPATeste.Facade.ITarefasFachadas;
import br.com.ifba.JPATeste.Models.Tarefas;
import br.com.ifba.JPATeste.Instancias.TarefaInstance;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lara
 */
public class Tela1 extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private TableRowSorter<DefaultTableModel> sorter;
    private ITarefasFachadas facade;

    public Tela1() {
        initComponents();
        facade = new TarefasFachadas(); //inicia uma fachada
        addRowToTable(); // inicia atabela preenchda
        tableModel = (DefaultTableModel) jTable1.getModel();
        sorter = new TableRowSorter<>(tableModel);
        jTable1.setRowSorter(sorter);//inica o sorte pro filtro 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "Finalizada", "Data Adicionada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 620, 300));

        btnAdd.setText("+");
        btnAdd.setToolTipText("Adicionar nova tarefa");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 50, 30));

        txtBuscar.setToolTipText("Buscar Tarefa");
        txtBuscar.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtBuscarInputMethodTextChanged(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 90, 30));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 100, 30));

        jLabel1.setText("TAREFAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Tela2 tela2 = new Tela2(this);
        tela2.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {//erro handling
            int i = jTable1.getSelectedRow();
            if (i != -1) {
                long iId = (long) jTable1.getValueAt(i, 0);
                facade.delete(iId);
                updateTable();
            } else {
                JOptionPane.showMessageDialog(this, "Nehuma tarefa selecionada", "Erro", JOptionPane.ERROR_MESSAGE);
            }

        } catch (TarefaExceptions ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int i = jTable1.getSelectedRow();
        long iId = (long) jTable1.getValueAt(i, 0);
        Tarefas selectedTarefa = TarefaInstance.createInstance();
        selectedTarefa = facade.read(iId);

        if (selectedTarefa != null) {
            Tela3 updateDialog = new Tela3(this, selectedTarefa);
            updateDialog.setVisible(true);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        filtrarTable();
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void txtBuscarInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtBuscarInputMethodTextChanged
        filtrarTable();
    }//GEN-LAST:event_txtBuscarInputMethodTextChanged

    private void filtrarTable() {
        String searchText = txtBuscar.getText().trim().toLowerCase();

        if (searchText.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText, 1)); // Filter by column 1 (name) case-insensitively
        }
    }

    public void addRowToTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        ArrayList<Tarefas> tarefas = (ArrayList<Tarefas>) facade.readAll();

        Object[] row = new Object[4];

        for (Tarefas tarefa : tarefas) {
            row[0] = tarefa.getId();
            row[1] = tarefa.getDescricao();
            row[2] = tarefa.isFinalizado();
            row[3] = tarefa.getDataFinal().getTime();
            model.addRow(row);
        }
        jTable1.setModel(model);
        repaint();
    }

    public void updateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        addRowToTable();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
